# Generated by Django 4.2 on 2023-04-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('DI', 'Dinheiro'), ('CC', 'Cartão de Crédito'), ('DC', 'Cartão de Débito')], default='CA', max_length=2),
        ),
    ]
